spring.application.name=student-server
spring.config.import=optional:file:.env[.properties]

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Let Hibernate create/update tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Handle CORS so your web/flutter apps can talk to this backend
# We'll add a config class for this later if needed.